### ISSUE TITLE
现在是不是不支持RTSP 协议？

### ISSUE THREAD

**Issue by zjianflys** [HMS-Core/hms-video-demo-android#3]

**Comment by zjianflys** [comment]
我试了一下 确实不支持，后期有支持的打算嘛？

**Comment by Xuejiao-Shi** [comment]
您好，感谢您的提问，与产品团队确认目前暂无支持RTSP协议的计划，请您提供下您的应用信息（应用名称，appID），我们将据此跟产品团队沟通。

**Comment by zjianflys** [comment]
我只是在测试您开源的项目  谢谢回复！！！支持华为！！！
